proxies:
- name: 🇳🇱 NL-114
  type: wireguard
  server: 149.34.244.139
  port: 51820
  ip: 10.2.0.2
  private-key: kIqW5huV/2Zg2PoOmf+cmRscAIvUMGT+22nnlWcJKEE=
  public-key: cZqPUUEdnSZVoKckIHHTfvS/lKEG5mslwHiPJsSG1FE=
  allowed-ips: ['0.0.0.0/0']
  udp: true
  mtu: 1420
  remote-dns-resolve: true
  dns: [10.2.0.1]
  amnezia-wg-option:
    jc: 30
    jmin: 10
    jmax: 30
    s1: 0
    s2: 0
    h1: 1
    h2: 2
    h3: 3
    h4: 4

proxy-groups:
- name: Proton
  type: select
  icon: https://res.cloudinary.com/dbulfrlrz/image/upload/v1703162849/static/logos/icons/vpn_f9embt.svg
  proxies:
    - 🇳🇱 NL-114
  url: 'http://speed.cloudflare.com/'
  unified-delay: true
  interval: 300