proxies:
- name: 🇳🇱 NL-202
  type: wireguard
  server: 194.59.6.5
  port: 51820
  ip: 10.2.0.2
  private-key: 6OGq3lpF4PxeP4KXmCG/bMBXDxeLxVqxfPAzThYeZ0Q=
  public-key: H4qyuy/1uYb0Wsm6q5eq0qdx5EE+viBt4SkvuEmSMjk=
  allowed-ips: ['0.0.0.0/1', '128.0.0.0/1']
  udp: true
  mtu: 1420
  remote-dns-resolve: true
  dns: [10.2.0.1]
  amnezia-wg-option:
    jc: 3
    jmin: 1
    jmax: 3
    s1: 0
    s2: 0
    h1: 1
    h2: 2
    h3: 3
    h4: 4

proxy-groups:
- name: Proton
  type: select
  icon: https://res.cloudinary.com/dbulfrlrz/image/upload/v1703162849/static/logos/icons/vpn_f9embt.svg
  proxies:
    - 🇳🇱 NL-202
  url: 'http://speed.cloudflare.com/'
  unified-delay: true
  interval: 300
